local tu = require('tests.utils')

local PATH = './tests/sample/index.cs'
local LANG = 'c_sharp'
local MODE = 'join'

local data = {
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "attribute_list", preset default',
    cursor = { 11, 0 },
    expected = { 6, 8 },
    result = { 10, 12 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "attribute", preset default',
    cursor = { 22, 1 },
    expected = { 17, 19 },
    result = { 21, 23 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "type_parameter_list", preset default',
    cursor = { 33, 2 },
    expected = { 28, 29 },
    result = { 31, 32 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "enum_member_declaration_list", preset default',
    cursor = { 42, 2 },
    expected = { 37, 38 },
    result = { 40, 41 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "enum_declaration", preset default',
    cursor = { 51, 0 },
    expected = { 47, 48 },
    result = { 50, 51 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "delegate_declaration", preset default',
    cursor = { 61, 13 },
    expected = { 57, 58 },
    result = { 60, 61 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "constructor_declaration", preset default',
    cursor = { 72, 9 },
    expected = { 68, 69 },
    result = { 71, 72 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "method_declaration", preset default',
    cursor = { 82, 14 },
    expected = { 78, 79 },
    result = { 81, 82 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "accessor_list", preset default',
    cursor = { 93, 4 },
    expected = { 88, 89 },
    result = { 91, 92 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "bracketed_parameter_list", preset default',
    cursor = { 101, 17 },
    expected = { 97, 98 },
    result = { 100, 101 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "block", preset default',
    cursor = { 110, 26 },
    expected = { 106, 107 },
    result = { 109, 110 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "indexer_declaration", preset default',
    cursor = { 119, 13 },
    expected = { 115, 116 },
    result = { 118, 119 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "operator_declaration", preset default',
    cursor = { 128, 24 },
    expected = { 124, 125 },
    result = { 127, 128 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "conversion_operator_declaration", preset default',
    cursor = { 137, 16 },
    expected = { 133, 134 },
    result = { 136, 137 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "constructor_initializer", preset default',
    cursor = { 145, 37 },
    expected = { 141, 142 },
    result = { 144, 145 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "tuple_type", preset default',
    cursor = { 156, 4 },
    expected = { 151, 152 },
    result = { 154, 155 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "invocation_expression", preset default',
    cursor = { 175, 4 },
    expected = { 171, 172 },
    result = { 174, 175 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "object_creation_expression", preset default',
    cursor = { 184, 16 },
    expected = { 180, 181 },
    result = { 183, 184 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "implicit_object_creation_expression", preset default',
    cursor = { 193, 18 },
    expected = { 189, 190 },
    result = { 192, 193 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "type_argument_list", preset default',
    cursor = { 203, 6 },
    expected = { 198, 199 },
    result = { 201, 202 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "initializer_expression", preset default',
    cursor = { 212, 6 },
    expected = { 207, 208 },
    result = { 210, 211 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "collection_expression", preset default',
    cursor = { 222, 6 },
    expected = { 217, 218 },
    result = { 220, 221 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "element_binding_expression", preset default',
    cursor = { 232, 6 },
    expected = { 227, 228 },
    result = { 230, 231 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "bracketed_argument_list", preset default',
    cursor = { 241, 6 },
    expected = { 236, 237 },
    result = { 239, 240 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "element_access_expression", preset default',
    cursor = { 249, 15 },
    expected = { 245, 246 },
    result = { 248, 249 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "tuple_expression", preset default',
    cursor = { 259, 6 },
    expected = { 254, 255 },
    result = { 257, 258 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "switch_expression", preset default',
    cursor = { 267, 21 },
    expected = { 263, 264 },
    result = { 266, 267 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "list_pattern", preset default',
    cursor = { 277, 6 },
    expected = { 272, 273 },
    result = { 275, 276 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "property_pattern_clause", preset default',
    cursor = { 287, 6 },
    expected = { 282, 283 },
    result = { 285, 286 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "if_statement", preset default',
    cursor = { 295, 4 },
    expected = { 291, 292 },
    result = { 294, 295 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "while_statement", preset default',
    cursor = { 304, 4 },
    expected = { 300, 301 },
    result = { 303, 304 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "do_statement", preset default',
    cursor = { 313, 4 },
    expected = { 309, 310 },
    result = { 312, 313 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "for_statement", preset default',
    cursor = { 322, 4 },
    expected = { 318, 319 },
    result = { 321, 322 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "foreach_statement", preset default',
    cursor = { 331, 4 },
    expected = { 327, 328 },
    result = { 330, 331 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "using_statement", preset default',
    cursor = { 340, 4 },
    expected = { 336, 337 },
    result = { 339, 340 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "lock_statement", preset default',
    cursor = { 349, 4 },
    expected = { 345, 346 },
    result = { 348, 349 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "checked_statement", preset default',
    cursor = { 358, 4 },
    expected = { 354, 355 },
    result = { 357, 358 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "unsafe_statement", preset default',
    cursor = { 367, 4 },
    expected = { 363, 364 },
    result = { 366, 367 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "fixed_statement", preset default',
    cursor = { 376, 4 },
    expected = { 372, 373 },
    result = { 375, 376 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "try_statement", preset default',
    cursor = { 385, 4 },
    expected = { 381, 382 },
    result = { 384, 385 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "catch_clause", preset default',
    cursor = { 393, 22 },
    expected = { 389, 390 },
    result = { 392, 393 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "finally_clause", preset default',
    cursor = { 401, 62 },
    expected = { 397, 398 },
    result = { 400, 401 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "local_function_statement", preset default',
    cursor = { 409, 9 },
    expected = { 405, 406 },
    result = { 408, 409 },
  },
}

local treesj = require('treesj')
local opts = {}
treesj.setup(opts)

describe('TreeSJ ' .. MODE:upper() .. ':', function()
  for _, value in ipairs(data) do
    tu._test_format(value, treesj)
  end
end)
