local tu = require('tests.utils')

local PATH = './tests/sample/index.cs'
local LANG = 'c_sharp'
local MODE = 'split'

local data = {
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "attribute_list", preset default',
    cursor = { 7, 0 },
    expected = { 10, 15 },
    result = { 6, 11 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "attribute", preset default',
    cursor = { 18, 1 },
    expected = { 21, 26 },
    result = { 17, 22 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "type_parameter_list", preset default',
    cursor = { 29, 11 },
    expected = { 31, 35 },
    result = { 28, 32 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "enum_member_declaration_list", preset default',
    cursor = { 38, 12 },
    expected = { 40, 45 },
    result = { 37, 42 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "enum_declaration", preset default',
    cursor = { 48, 0 },
    expected = { 50, 55 },
    result = { 47, 52 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "delegate_declaration", preset default',
    cursor = { 58, 13 },
    expected = { 60, 64 },
    result = { 57, 61 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "constructor_declaration", preset default',
    cursor = { 69, 9 },
    expected = { 71, 76 },
    result = { 68, 73 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "method_declaration", preset default',
    cursor = { 79, 14 },
    expected = { 81, 86 },
    result = { 78, 83 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "accessor_list", preset default',
    cursor = { 89, 23 },
    expected = { 91, 95 },
    result = { 88, 92 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "bracketed_parameter_list", preset default',
    cursor = { 98, 17 },
    expected = { 100, 104 },
    result = { 97, 101 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "block", preset default',
    cursor = { 107, 26 },
    expected = { 109, 113 },
    result = { 106, 110 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "indexer_declaration", preset default',
    cursor = { 116, 13 },
    expected = { 118, 122 },
    result = { 115, 119 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "operator_declaration", preset default',
    cursor = { 125, 24 },
    expected = { 127, 131 },
    result = { 124, 128 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "conversion_operator_declaration", preset default',
    cursor = { 134, 16 },
    expected = { 136, 139 },
    result = { 133, 136 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "constructor_initializer", preset default',
    cursor = { 142, 37 },
    expected = { 144, 149 },
    result = { 141, 146 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "tuple_type", preset default',
    cursor = { 152, 10 },
    expected = { 154, 158 },
    result = { 151, 155 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "invocation_expression", preset default',
    cursor = { 172, 4 },
    expected = { 174, 178 },
    result = { 171, 175 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "object_creation_expression", preset default',
    cursor = { 181, 16 },
    expected = { 183, 187 },
    result = { 180, 184 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "implicit_object_creation_expression", preset default',
    cursor = { 190, 18 },
    expected = { 192, 196 },
    result = { 189, 193 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "type_argument_list", preset default',
    cursor = { 199, 31 },
    expected = { 201, 205 },
    result = { 198, 202 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "initializer_expression", preset default',
    cursor = { 208, 33 },
    expected = { 210, 215 },
    result = { 207, 212 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "collection_expression", preset default',
    cursor = { 218, 20 },
    expected = { 220, 225 },
    result = { 217, 222 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "element_binding_expression", preset default',
    cursor = { 228, 21 },
    expected = { 230, 234 },
    result = { 227, 231 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "bracketed_argument_list", preset default',
    cursor = { 237, 20 },
    expected = { 239, 243 },
    result = { 236, 240 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "element_access_expression", preset default',
    cursor = { 246, 15 },
    expected = { 248, 252 },
    result = { 245, 249 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "tuple_expression", preset default',
    cursor = { 255, 16 },
    expected = { 257, 261 },
    result = { 254, 258 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "switch_expression", preset default',
    cursor = { 264, 21 },
    expected = { 266, 270 },
    result = { 263, 267 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "list_pattern", preset default',
    cursor = { 273, 18 },
    expected = { 275, 280 },
    result = { 272, 277 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "property_pattern_clause", preset default',
    cursor = { 283, 18 },
    expected = { 285, 289 },
    result = { 282, 286 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "if_statement", preset default',
    cursor = { 292, 4 },
    expected = { 294, 298 },
    result = { 291, 295 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "while_statement", preset default',
    cursor = { 301, 4 },
    expected = { 303, 307 },
    result = { 300, 304 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "do_statement", preset default',
    cursor = { 310, 4 },
    expected = { 312, 316 },
    result = { 309, 313 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "for_statement", preset default',
    cursor = { 319, 4 },
    expected = { 321, 325 },
    result = { 318, 322 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "foreach_statement", preset default',
    cursor = { 328, 4 },
    expected = { 330, 334 },
    result = { 327, 331 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "using_statement", preset default',
    cursor = { 337, 4 },
    expected = { 339, 343 },
    result = { 336, 340 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "lock_statement", preset default',
    cursor = { 346, 4 },
    expected = { 348, 352 },
    result = { 345, 349 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "checked_statement", preset default',
    cursor = { 355, 4 },
    expected = { 357, 361 },
    result = { 354, 358 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "unsafe_statement", preset default',
    cursor = { 364, 4 },
    expected = { 366, 370 },
    result = { 363, 367 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "fixed_statement", preset default',
    cursor = { 373, 4 },
    expected = { 375, 379 },
    result = { 372, 376 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "try_statement", preset default',
    cursor = { 382, 4 },
    expected = { 384, 387 },
    result = { 381, 384 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "catch_clause", preset default',
    cursor = { 390, 22 },
    expected = { 392, 395 },
    result = { 389, 392 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "finally_clause", preset default',
    cursor = { 398, 62 },
    expected = { 400, 403 },
    result = { 397, 400 },
  },
  {
    path = PATH,
    mode = MODE,
    lang = LANG,
    desc = 'lang "%s", node "local_function_statement", preset default',
    cursor = { 406, 9 },
    expected = { 408, 413 },
    result = { 405, 410 },
  },
}

local treesj = require('treesj')
local opts = {}
treesj.setup(opts)

describe('TreeSJ ' .. MODE:upper() .. ':', function()
  for _, value in ipairs(data) do
    tu._test_format(value, treesj)
  end
end)
